runtime: go120
main: cmd/api/main.go
env_variables:
  SERVER_PORT: 8080

handlers:
  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$
  - url: /.*
    script: auto
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_pending_latency: 5000ms