name: Create Tag and Release

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-tag-and-release:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Calculate new version
      id: calculate_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        tag_prefix: ''

    - name: Update version in Swagger Documentation
      if: ${{ github.event_name != 'pull_request' }}
      continue-on-error: false
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq '.info.version = $newValue' --arg newValue '${{ steps.calculate_version.outputs.new_tag }}' <<<$(cat schema/openapi.v3.json) > schema/openapi.v3.json

    - name: Commit changes
      if: ${{ github.event_name != 'pull_request' }}
      id: update_version
      continue-on-error: false
      uses: test-room-7/action-update-file@v1
      with:
        file-path: schema/openapi.v3.json
        commit-msg: "Updated version"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version and push tag
      id: tag_version
      if: ${{ github.event_name != 'pull_request' }}
      continue-on-error: false
      uses: mathieudutour/github-tag-action@v6.1
      with:
        commit_sha: ${{ steps.update_version.outputs.commit-sha }}
        tag_prefix: ''
        github_token: ${{ secrets.PAT }}
        custom_tag: ${{ steps.calculate_version.outputs.new_tag }}

    - name: Create a GitHub release
      if: ${{ github.event_name != 'pull_request' }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.calculate_version.outputs.new_tag }}
        name: Release ${{ steps.calculate_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
