name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Pass the received secret to an action
    uses: ./.github/workflows/deploy.yaml
    with:
      image: ghcr.io/davehornigan/movies-api:1.0.11
      ssh-host: ${{ vars.PUBLISH_SERVER_HOST }}
      ssh-user: ${{ vars.PUBLISH_SERVER_USER }}
      ssh-port: ${{ vars.PUBLISH_SERVER_PORT }}
      api-port: ${{ vars.API_PORT }}
      tmdb-api-host: ${{ vars.TMDB_API_SERVER }}
    secrets: inherit
#      TMDB_API_ACCESS_TOKEN: ${{ secrets.TMDB_API_ACCESS_TOKEN }}
#      PUBLISH_SERVER_HOST: ${{ secrets.PUBLISH_SERVER_HOST }}
#      PUBLISH_SSH_PRIVATE_KEY: ${{ secrets.PUBLISH_SSH_PRIVATE_KEY }}