name: Test

on:
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  meta:
    name: Meta
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags[0] }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            davehornigan/movies-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

  test:
    if: ${{ needs.build-and-push-image.outputs.image-tag != '' }}
    name: Pass the received secret to an action
    uses: ./.github/workflows/deploy.yaml
    needs:
      - meta
    with:
      image: ${{ needs.meta.outputs.image-tag }}
      ssh-host: ${{ vars.PUBLISH_SERVER_HOST }}
      ssh-user: ${{ vars.PUBLISH_SERVER_USER }}
      ssh-port: ${{ vars.PUBLISH_SERVER_PORT }}
      api-port: ${{ vars.API_PORT }}
      tmdb-api-host: ${{ vars.TMDB_API_SERVER }}
    secrets: inherit
#      TMDB_API_ACCESS_TOKEN: ${{ secrets.TMDB_API_ACCESS_TOKEN }}
#      PUBLISH_SERVER_HOST: ${{ secrets.PUBLISH_SERVER_HOST }}
#      PUBLISH_SSH_PRIVATE_KEY: ${{ secrets.PUBLISH_SSH_PRIVATE_KEY }}